name: Node.js Package Lint, Test and Publish

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
